version: 2.1
jobs:
  build_and_test:
    docker:
      - image: circleci/node:12.13
    steps:
      - checkout
      - restore_cache:
          key: npm-dependencies-{{ checksum "package.json" }}
      - run:
          name: Installing dependencies
          command: npm install
      - save_cache:
          key: npm-dependencies-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build
          command: npm run build
      - run:
          name: Run tests
          command: npm run test:ci
      - store_test_results:
          path: ./junit.xml

workflows:
  version: 2
  build:
    jobs:
      - build_and_test
